development:
  port: 3312
  mem_limit: 128M
  min_prefix_len: 3
  max_matches: <%= MAX_SPHINX_RESULTS %>
fastdev:
  port: 3312
  mem_limit: 128M
  min_prefix_len: 3
  max_matches: <%= MAX_SPHINX_RESULTS %>
test:
  port: 3313
  mem_limit: 128M
  min_prefix_len: 3
  max_matches: <%= MAX_SPHINX_RESULTS %>
production:
  port: 3312
  mem_limit: 128M
  min_prefix_len: 3
  max_matches: <%= MAX_SPHINX_RESULTS %>
